### ISSUE TITLE
modifying an addSelect at runtime

### ISSUE THREAD

**Issue by marcmerlin** [distrakt/OmEspHelpers#7]
Hi @distrakt , I have two needs to fill with addSelect

1) I need to change the select option that is shown as selected if it is updated from code. It's be great if it could happen on the displayed page (ajax refresh), but good enough if it works if I navigate to another tab and come back to this one

2) I also need to change the text at runtime.
- option1 (disabled)
- option2 (enabled)

would become
- option1 (enabled)
- option2 (enabled)

in the dropdown.
Are you able to help with either?  Thanks :)

**Comment by marcmerlin** [comment]
One way to do this would be to allow for the strings to be writeable instead of const, and then I can update them in my code.
I'd still have to trigger a reload of the page, or the widget, but it would then render with the updated string.
Does that sound reasonable?

**Comment by marcmerlin** [comment]
@distrakt  howdy. I needed this again, so I tried that:
```
void build_register_page() {
    if (p) {
	delete(p);
	read_config_index();
    }
    p = new OmWebPages();
(fill the page)
    p->addSelect("Choose Demo", actionProc, 2, HTML_DEMOCHOICE);
    for loop ( p->addSelectOption(option, i); )
    s.setHandler(*p)
}
```
This works, but not really, because it leaks memory like a sieve.

I clean the object and the strings allocated on my side (I use char * and keep the pointers to free later, not String).  
However, I looked your code, and the first problem is that the char * are copied to arduino String, and I'm guessing they are never freed when the object is destroyed.
Also, I naively tried to free the vectors, but that's redundant, I think deleting the pageselect would do it (except freeing the arduino Strings maybe?), 
```
class PageSelect : public PageItem
{
public:
    ~PageSelect() { optionNames.clear(); optionNumbers.clear(); };
    OmWebActionProc proc = 0;
    std::vector<String> optionNames;
    std::vector<int> optionNumbers;
```

however I think those pageselect objects get linked in addselect
```
OmWebPageItem *OmWebPages::addSelect(const char *itemName, OmWebActionProc proc, int value, int ref1, void *ref2)
{
    PageSelect *p = new PageSelect();
    p->name = itemName;
    p->value = value;
    p->ref1 = ref1;
    p->ref2 = ref2;
    p->proc = proc;
    this->currentPage->addItem(p);
    this->currentSelect = p;
    return &p->item;
}
```
and I'm not sure I saw any garbage collection of those items when the main OmWebPages object is freed.

Would you agree with what I think I read? If so, would you feel it's not too much work to make sure that delete(p) actually clears all allocated stuff, or it's non trivial?

**Comment by marcmerlin** [comment]
Ok, here is a very dirty partial patch. This stops the biggest percentage of the leak for me, but each page rebuild still leaks 4KB, so I can only rebuild the page a few times before I run out of RAM and my code crashes.
Getting rid of arduino String wherever possible will help, and the more work to make sure that each object keeps track of its allocations and deletes them in the destructor.

Of course, this patch changes the interface in that the caller can't just send strings that go out of scope and get deleted, they are now the only copy and must be maintained and deleted by the caller.
And if case you wonder, I have a dropdown with 300 elements each 30 bytes or so. That's about 10K just in strings, so I can't afford to leak or duplicate them. Also, a bonus on having me handle them is that I use ps_malloc and they go to PSRAM, of which I have 4MB, so that helps.
```
--- a/src/OmWebPages.cpp
+++ b/src/OmWebPages.cpp
@@ -303,11 +303,12 @@ public:
 class PageSelect : public PageItem
 {
 public:
     OmWebActionProc proc = 0;
-    std::vector<String> optionNames;
+    std::vector<const char *> optionNames;
     std::vector<int> optionNumbers;
 
-    void addOption(String optionName, int optionNumber)
+    void addOption(const char *optionName, int optionNumber)
     {
         this->optionNames.push_back(optionName);
         this->optionNumbers.push_back(optionNumber);
@@ -339,7 +340,7 @@ public:
                 w.addAttribute("selected", "selected");
                 foundSelectedOption = true;
             }
-            w.addContent(this->optionNames[ix].c_str());
+            w.addContent(this->optionNames[ix]);
             w.endElement();
         }
```

**Comment by distrakt** [comment]
Thanks for these details!

I do have mixed feelings about string vs char *. string makes it easier to safely/dynamically create labels, but as you point out at cost of copying and fragmentation... must ponder that part.

I'm adding proper destructors which need further testing but at first blush appear to clean up on delete omWebPages ok.

ALSO -- p.beginPage(pageNameThatAlreadyExists) will now clear the items off just that page, and and set that as the "current" page that p.addButton() et al applies to. Allocation could still have fragmentation issues, and deleting everything may still have its benefits. checking in shortly.

**Comment by marcmerlin** [comment]
Thank you, while https://github.com/distrakt/OmEspHelpers/pull/8 will further help with memory use, I can confirm master allows recreating the page and no memory is leaked, thank you
